image: node:10

stages:
  - install
  - build
  - quality
  - pages

# Install
install:
   stage: install
   script:
      - npm install
   artifacts:
      name: "artifacts"
      untracked: true
      expire_in: 30 mins
      paths:
        - .npm/
        - node_modules/

# Build
build:
  stage: build
  script:
    - CI=false npm run build-storybook
  artifacts:
    paths:
      - build
    expire_in: 60 mins
  dependencies:
    - install

# Unit test
test:unit:
   stage: quality
   script:
      -  npm run test
   dependencies:
      - install

# Pages
pages:
  stage: pages
  cache:
    paths:
    - node_modules/

  script:
  - npm update
  - npm install
  - yarn build-storybook -o ./public
  artifacts:
    paths:
    - public
  only:
  - master

