image: node:10

stages:
  - install
  - pages
  - quality

# Install
install:
   stage: install
   script:
      - npm install
   artifacts:
      name: "artifacts"
      untracked: true
      expire_in: 30 mins
      paths:
        - .npm/
        - node_modules/

# Build
pages:
  stage: pages
  script:
    - CI=false npm run build-storybook -o ./public
  artifacts:
    paths:
      - public
    expire_in: 60 mins
  dependencies:
    - install

# Unit test
test:unit:
   stage: quality
   script:
      -  npm run test
   dependencies:
      - install
